version: '3.7'
services:
  frontend_service:
    container_name: movie-gen_frontend_service
    build: ./service_1
    image: jsaadat01/frontend_service_image:latest
    ports:
    - target: 5000
      published: 5000
  
  location_service:
    container_name: movie-gen_location_service
    build: ./service_2
    image: jsaadat01/location_service_image:latest

  weather_service:
    container_name: movie-gen_weather_service
    build: ./service_3
    image: jsaadat01/weather_service_image:latest

  movie_service:
    container_name: movie-gen_movie_service
    build: ./service_4
    image: jsaadat01/movie_service_image:latest